import type { TrackConfig } from '../types';

// Auto-detection mapping: Excel column names -> standard curve names
export const COLUMN_NAME_MAP: Record<string, string> = {
  'md': 'MD',
  'measured_depth': 'MD',
  'measured depth': 'MD',
  'depth': 'MD',
  'tvd': 'TVD',
  'true_vertical_depth': 'TVD',
  'true vertical depth': 'TVD',
  'phie': 'PHIE',
  'porosity': 'PHIE',
  'effective_porosity': 'PHIE',
  'por': 'PHIE',
  'perm': 'PERM',
  'permeability': 'PERM',
  'k': 'PERM',
  'kh': 'PERM',
  'sw': 'SW',
  'water_saturation': 'SW',
  'water saturation': 'SW',
  'swat': 'SW',
  'net_pay': 'NETPAY',
  'net pay': 'NETPAY',
  'netpay': 'NETPAY',
  'nettopay': 'NETPAY',
  'pay': 'NETPAY',
  'gr': 'GR',
  'gamma_ray': 'GR',
  'gamma ray': 'GR',
  'gamma': 'GR',
  'rt': 'RT',
  'resistivity': 'RT',
  'res': 'RT',
  'ild': 'RT',
  'rhob': 'RHOB',
  'density': 'RHOB',
  'bulk_density': 'RHOB',
  'nphi': 'NPHI',
  'neutron': 'NPHI',
  'neutron_porosity': 'NPHI',
  'vcl': 'VCL',
  'clay_volume': 'VCL',
  'vshale': 'VCL',
  'vsh': 'VCL',
  // Petroview mnemonics
  'rop5': 'ROP5',
  'sppa': 'SPPA',
  'hkla': 'HKLA',
  'mfia': 'MFIA',
  'tdra': 'TDRA',
  'rpma': 'RPMA',
  'tqa': 'TQA',
  'woba': 'WOBA',
  'bpos': 'BPOS',
  'dbtm': 'MD',
  'dmea': 'MD',
  'dept': 'MD',
  'tvdss': 'TVD',
  'ecdtd': 'ECDTD',
  'mwi': 'MWI',
  'mwo': 'MWO',
  'ecd': 'ECD',
  'incl': 'INCL',
  'azim': 'AZIM',
  'dls': 'DLS',
};

// Curve metadata with display properties
export interface CurveDefaults {
  scaleMin: number;
  scaleMax: number;
  scaleType: 'linear' | 'logarithmic';
  color: string;
  fillColor?: string;
  fillLeft?: boolean;
  fillRight?: boolean;
  unit: string;
  description: string;
  gridLines: number;
}

export const CURVE_DEFAULTS: Record<string, CurveDefaults> = {
  GR: {
    scaleMin: 0,
    scaleMax: 150,
    scaleType: 'linear',
    color: '#15803d',
    fillColor: 'rgba(21, 128, 61, 0.3)',
    fillLeft: true,
    unit: 'API',
    description: 'Gamma Ray',
    gridLines: 5,
  },
  PHIE: {
    scaleMin: 0,
    scaleMax: 0.4,
    scaleType: 'linear',
    color: '#16a34a',
    fillColor: 'rgba(22, 163, 74, 0.3)',
    fillLeft: true,
    unit: 'v/v',
    description: 'Effective Porosity',
    gridLines: 4,
  },
  PERM: {
    scaleMin: 0.1,
    scaleMax: 10000,
    scaleType: 'logarithmic',
    color: '#dc2626',
    unit: 'mD',
    description: 'Permeability',
    gridLines: 4,
  },
  SW: {
    scaleMin: 0,
    scaleMax: 1,
    scaleType: 'linear',
    color: '#2563eb',
    fillColor: 'rgba(37, 99, 235, 0.3)',
    fillRight: true,
    unit: 'frac',
    description: 'Water Saturation',
    gridLines: 5,
  },
  NETPAY: {
    scaleMin: 0,
    scaleMax: 1,
    scaleType: 'linear',
    color: '#ca8a04',
    fillColor: 'rgba(202, 138, 4, 0.3)',
    fillLeft: true,
    unit: 'flag',
    description: 'Net Pay',
    gridLines: 2,
  },
  RT: {
    scaleMin: 0.2,
    scaleMax: 2000,
    scaleType: 'logarithmic',
    color: '#171717',
    unit: 'ohm.m',
    description: 'Resistivity',
    gridLines: 4,
  },
  RHOB: {
    scaleMin: 1.95,
    scaleMax: 2.95,
    scaleType: 'linear',
    color: '#dc2626',
    unit: 'g/cc',
    description: 'Bulk Density',
    gridLines: 4,
  },
  NPHI: {
    scaleMin: 0.45,
    scaleMax: -0.15,
    scaleType: 'linear',
    color: '#2563eb',
    unit: 'v/v',
    description: 'Neutron Porosity',
    gridLines: 4,
  },
  VCL: {
    scaleMin: 0,
    scaleMax: 1,
    scaleType: 'linear',
    color: '#92400e',
    fillColor: 'rgba(146, 64, 14, 0.3)',
    fillLeft: true,
    unit: 'frac',
    description: 'Clay Volume',
    gridLines: 5,
  },
  ROP5: {
    scaleMin: 0,
    scaleMax: 100,
    scaleType: 'linear',
    color: '#0891b2',
    unit: 'm/hr',
    description: 'Rate of Penetration (5ft avg)',
    gridLines: 5,
  },
  SPPA: {
    scaleMin: 0,
    scaleMax: 5000,
    scaleType: 'linear',
    color: '#7c3aed',
    unit: 'psi',
    description: 'Standpipe Pressure',
    gridLines: 5,
  },
  HKLA: {
    scaleMin: -50,
    scaleMax: 50,
    scaleType: 'linear',
    color: '#e11d48',
    unit: 'klbs',
    description: 'Hookload',
    gridLines: 5,
  },
  MFIA: {
    scaleMin: 0,
    scaleMax: 1200,
    scaleType: 'linear',
    color: '#059669',
    unit: 'gpm',
    description: 'Mud Flow In',
    gridLines: 4,
  },
  TDRA: {
    scaleMin: 0,
    scaleMax: 200,
    scaleType: 'linear',
    color: '#d97706',
    unit: 'klb-ft',
    description: 'Torque',
    gridLines: 4,
  },
  RPMA: {
    scaleMin: 0,
    scaleMax: 250,
    scaleType: 'linear',
    color: '#6366f1',
    unit: 'rpm',
    description: 'Rotary Speed',
    gridLines: 5,
  },
  TQA: {
    scaleMin: 0,
    scaleMax: 200,
    scaleType: 'linear',
    color: '#f97316',
    unit: 'klb-ft',
    description: 'Torque Average',
    gridLines: 4,
  },
  WOBA: {
    scaleMin: 0,
    scaleMax: 50,
    scaleType: 'linear',
    color: '#ef4444',
    unit: 'klbs',
    description: 'Weight on Bit',
    gridLines: 5,
  },
  BPOS: {
    scaleMin: 0,
    scaleMax: 50,
    scaleType: 'linear',
    color: '#64748b',
    unit: 'm',
    description: 'Block Position',
    gridLines: 5,
  },
  ECDTD: {
    scaleMin: 1.0,
    scaleMax: 2.5,
    scaleType: 'linear',
    color: '#be185d',
    unit: 'sg',
    description: 'ECD at TD',
    gridLines: 4,
  },
  MWI: {
    scaleMin: 1.0,
    scaleMax: 2.5,
    scaleType: 'linear',
    color: '#0d9488',
    unit: 'sg',
    description: 'Mud Weight In',
    gridLines: 4,
  },
  MWO: {
    scaleMin: 1.0,
    scaleMax: 2.5,
    scaleType: 'linear',
    color: '#4f46e5',
    unit: 'sg',
    description: 'Mud Weight Out',
    gridLines: 4,
  },
  ECD: {
    scaleMin: 1.0,
    scaleMax: 2.5,
    scaleType: 'linear',
    color: '#db2777',
    unit: 'sg',
    description: 'Equivalent Circulating Density',
    gridLines: 4,
  },
  INCL: {
    scaleMin: 0,
    scaleMax: 100,
    scaleType: 'linear',
    color: '#0284c7',
    unit: 'deg',
    description: 'Inclination',
    gridLines: 5,
  },
  AZIM: {
    scaleMin: 0,
    scaleMax: 360,
    scaleType: 'linear',
    color: '#7e22ce',
    unit: 'deg',
    description: 'Azimuth',
    gridLines: 4,
  },
  DLS: {
    scaleMin: 0,
    scaleMax: 10,
    scaleType: 'linear',
    color: '#c2410c',
    unit: 'deg/30m',
    description: 'Dogleg Severity',
    gridLines: 5,
  },
};

export const DEFAULT_TRACK_WIDTH = 150;
export const DEPTH_TRACK_WIDTH = 70;
export const DEFAULT_NULL_VALUE = -999.25;

export function createDefaultTrackConfig(curveName: string, id: string): TrackConfig {
  const defaults = CURVE_DEFAULTS[curveName];
  if (!defaults) {
    return {
      id,
      curveNames: [curveName],
      scaleMin: 0,
      scaleMax: 1,
      scaleType: 'linear',
      width: DEFAULT_TRACK_WIDTH,
      color: '#94a3b8',
      gridLines: 5,
      visible: true,
    };
  }
  return {
    id,
    curveNames: [curveName],
    scaleMin: defaults.scaleMin,
    scaleMax: defaults.scaleMax,
    scaleType: defaults.scaleType,
    width: DEFAULT_TRACK_WIDTH,
    color: defaults.color,
    fillLeft: defaults.fillLeft,
    fillRight: defaults.fillRight,
    fillColor: defaults.fillColor,
    gridLines: defaults.gridLines,
    visible: true,
  };
}
